### ISSUE TITLE
Add ability to filter for specific items (include / exclude)

### ISSUE THREAD

**Issue by JoshStrobl** [DataDrake/eopkg-deps#1]
This is a feature request to add the ability to filter for specific items, or exclude them, when performing the following subcommands: `fwd`, `rev`, `ow`, such as via flags `-i / --include` and `-e / --exclude`. When it's set to an empty string (default value), no package name include / exclude would be performed and thus retain the current behavior.

Use case: I'm updating `gstreamer-1.0` and only want to see the reverse dependencies that are *other* gstreamer-1.0 packages, such as `gstreamer-1.0-plugins-bad`. Now while I *could* technically just pipe the output of `eopkg-deps` into `grep`, I may lose out on all the fancy output that's being done, instead of just being able to run something like `eopkg-deps rev gstreamer-1.0 -i 'gstreamer-'` or `eopkg-deps rev gstreamer-1.0 -e 'gst'`

**Comment by DataDrake** [comment]
Sooo. I'm going to handle this in the `ypkg` version so that we ignore patterns (think TeXLive). That will also solve the problem of not having to mark sub-packages in "todo mode".
